name: HSR_results
channels:
  - conda-forge
  - defaults
  - schrodinger
  - anaconda
dependencies:
  - numpy
  - oddt
  - pip
  - pymol
  - rdkit
  - scipy
  - anaconda::pyqt
  - conda-forge::tqdm
  - conda-forge::bs4
  - pip:
    - hsr
